name: epi2melabs-wf-transcript-target
channels:
    - epi2melabs
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python==3.8.*
    - aplanat >=0.4.0
    - pysam
    - fastcat
    - minimap2
    - samtools
    - racon
    - pomoxis
    - bamtools
    - python-edlib
    - biopython
    - mosdepth